### ISSUE TITLE
Unclear Wording / Possible Typo

### ISSUE THREAD

**Issue by ztw17** [learn-co-curriculum/fewpjs-introduction-to-the-dom-to-get-started#5] opened 2020-02-15 22:26 UTC
As written: The window variable points to an object **the** represents Chrome's information about the browser, well, "window."

Is this supposed to be: "... to an object **that** represents Chrome's information..." ?

**Comment by kierblk** [comment] 2020-03-01 00:06
Duplicate of #4

**Comment by lizbur10** [comment] 2021-01-08 15:42
Thank you for spotting this issue and providing feedback. We have updated the materials.

Thanks for contributing! 💙

**Closed as completed by lizbur10** 2021-01-08 15:42 UTC
